FROM node:alpine
WORKDIR /app
COPY package.json ./
RUN apk add --no-cache python3 make g++
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "npm", "start" ]



FROM node:16-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . .
EXPOSE 8000
CMD [ "npm", "run", "start" ]